# Generated by Django 3.1.4 on 2020-12-20 10:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20201220_1124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Profile',
        ),
    ]
