# Generated by Django 3.1.4 on 2020-12-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
