# Generated by Django 3.1.4 on 2020-12-28 19:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0002_auto_20201227_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
