# Generated by Django 3.1.4 on 2020-12-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0003_auto_20201228_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessage',
            options={},
        ),
    ]
