# Generated by Django 3.1.4 on 2020-12-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0004_auto_20201229_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='recipient_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='sender_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
